---
apiVersion: v1
kind: Secret
metadata:
  name: java-app-secret
  namespace: java-mysql
  labels:
    app.kubernetes.io/name: java-app
    app.kubernetes.io/component: credentials
    app.kubernetes.io/part-of: java-mysql-platform
type: Opaque
stringData:
  DB_USER: replace-me
  DB_PWD: replace-me