---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: java-mysql
  labels:
    app.kubernetes.io/name: phpmyadmin
    app.kubernetes.io/component: database-admin
    app.kubernetes.io/part-of: java-mysql-platform

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: phpmyadmin

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
      appProtocol: http